version: 2.1

orbs:
  android: circleci/android@2.4.0
  flutter: circleci/flutter@2.0.2
  ruby: circleci/ruby@2.1.0
  macos: circleci/macos@2.4.1

commands:
  install_macos_gem:
    description: >
      Install your MacOS Rubygems(mainly fastlane) with automated caching and best practices applied. Requires lock file.
      https://flutter.dev/docs/deployment/cd
    parameters:
      app-dir:
        default: .
        description: Path to the directory containing your pubspec.yaml file. Not needed if pubspec.yaml lives in the root.
        type: string
      cache-version:
        default: v1
        description: Change the default cache version if you need to clear the cache for any reason.
        type: string
    steps:
      - restore_cache:
          keys:
            - 'bundle-<<parameters.cache-version>>-macos-{{ checksum "<< parameters.app-dir >>/macos/Gemfile.lock" }}'
      - run:
          name: Install Dependencies
          command: |
            bundle config set path ./vendor/bundle
            bundle install
          working_directory: <<parameters.app-dir>>/macos
      - save_cache:
          paths:
            - <<parameters.app-dir>>/ios/vendor/bundle
          key: 'bundle-<<parameters.cache-version>>-macos-{{ checksum "<< parameters.app-dir >>/macos/Gemfile.lock" }}'
  install_macos_pods:
    description: >
      Install your MacOS cocoapods packages with automated caching and best practices applied. Requires lock file.
    parameters:
      app-dir:
        default: .
        description: Path to the directory containing your pubspec.yaml file. Not needed if pubspec.yaml lives in the root.
        type: string
      cache-version:
        default: v1
        description: Change the default cache version if you need to clear the cache for any reason.
        type: string
    steps:
      - restore_cache:
          keys:
            - 'pod-macos-<<parameters.cache-version>>-{{ checksum "<< parameters.app-dir >>/macos/Podfile.lock" }}'
      - run:
          name: Install Dependencies
          command: pod install
          working_directory: <<parameters.app-dir>>/macos
      - save_cache:
          paths:
            - <<parameters.app-dir>>/macos/Pods
          key: 'pod-macos-<<parameters.cache-version>>-{{ checksum "<< parameters.app-dir >>/macos/Podfile.lock" }}'

jobs:
  build_android:
    executor:
      name: android/android-machine
      resource-class: large
      tag: 2023.11.1
    steps:
      - checkout
      - flutter/install_sdk: 
          version: 3.16.5
      - flutter/install_pub:
          cache-version: v1
      - run:
          name: Flutter pub get
          command: |
            flutter pub get
      - run:
          name: Decode Android keystore
          command: |
            echo $BASE64_KEYSTORE | base64 -d | tee keystore android/app/keystore > /dev/null
      - run:
          name: Create keystore.properties
          command: |
            cd android && printf 'keyAlias=%s\nkeyPassword=%s\nstoreFile=keystore\nstorePassword=%s' \
            $RELEASE_KEY_ALIAS $RELEASE_KEY_PASSWORD $RELEASE_STORE_PASSWORD > key.properties
      - run:
          name: Print keystore.properties
          command: |
            cat android/key.properties
      - run:
          name: Build APK
          command: |
            flutter build appbundle
      - store_artifacts:
          path: build/app/outputs/bundle/release/app-release.aab
  build_ios:
    macos:
      xcode: 14.3.1
    steps:
      - checkout
      - flutter/install_sdk_and_pub: 
          version: 3.16.5
      - flutter/install_ios_pod
      - flutter/install_ios_gem
      - run:
          name: Flutter get packages
          command: flutter packages get
      - run:
          name: Install Cocoa Poads
          command: find . -name "Podfile" -execdir pod install \;
      - run:
          name: Flutter clean
          command: flutter clean
      - run:
          name: Flutter build
          command: flutter build ios --release --no-codesign
      - run:
          command: bundle exec fastlane release
          working_directory: ios
      - run: cat /Users/distiller/Library/Logs/gym/Runner-Runner.log
      - store_artifacts:
          path: /Users/distiller/project/ios/gogas-release.ipa
  build_macos:
    macos:
      xcode: 14.3.1
    steps:
      - checkout
      - run:
          name: Install Rosetta
          command: /usr/sbin/softwareupdate --install-rosetta --agree-to-license
      - flutter/install_sdk_and_pub: 
          version: 3.16.5
      - install_macos_pods
      - install_macos_gem
      - run:
          name: Flutter get packages
          command: flutter packages get
      - run:
          name: Install Cocoa Poads
          command: find . -name "Podfile" -execdir pod install \;
      - run:
          name: Flutter clean
          command: flutter clean
      - run:
          command: bundle exec fastlane prepare
          working_directory: macos
      - run:
          name: Flutter build
          command: flutter build macos --release
      - run:
          command: bundle exec fastlane release
          working_directory: macos
      - store_artifacts:
          path: /Users/distiller/project/macos/builds/gogas_delivery_app.pkg
workflows:
  build:
    jobs:
      - build_ios
      - build_android
      - build_macos