# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    setup_circle_ci
  end
  
  desc "Push a new release build to the App Store"
  lane :release do
    api_key = app_store_connect_api_key(
      key_id: "R89FDZP3WQ",
      issuer_id: "69a6de94-d2be-47e3-e053-5b8c7c11a4d1",
      key_filepath: "./fastlane/AuthKey_R89FDZP3WQ.p8",
      duration: 1200, # optional (maximum 1200)
      in_house: false # optional but may be required if using match/sigh
    )

    match(app_identifier: "bio.aequos.gogas.delivery", type: "appstore", verbose: true, readonly: false)
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner", output_name: "gogas-release.ipa")

    version = get_version_number(xcodeproj: "Runner.xcodeproj")
    upload_to_app_store(skip_metadata: true, skip_screenshots: true, app_version: version, run_precheck_before_submit: false, precheck_include_in_app_purchases: false)
  end
end
